Port scaner feature
cpp-park-vk-education/2023_1_RelayTeam pull request #2
Opened 2023-05-03 20:26 UTC by AlfaIV

Я изменял main. Там эти измениения остались, но их немного и они не критичные.

2023-05-03 22:22 UTC, Ant0nL0rd requested changes

2023-05-03 22:22 UTC, Ant0nL0rd commented on general_use/sources/networkTools.cpp
> +        assert(port <= 49151);
Использовать Q_ASSERT вместо assert.

2023-05-03 22:22 UTC, Ant0nL0rd commented on application/sources/main.cpp
> +    qDebug() << getPort(4000, 5000);
Откати main.cpp.

2023-05-03 22:22 UTC, Ant0nL0rd commented on general_use/sources/networkTools.cpp
> +        assert(startRangeSearch < stopRangeSearch);
Q_ASSERT

2023-05-03 22:22 UTC, Ant0nL0rd commented on gstreamer_interface/include/SessionManager.h
> +    qint16 getPort();
Что это здесь делает?

2023-05-03 22:22 UTC, Ant0nL0rd commented on gstreamer_interface/include/SessionManager.h
> +#include <QTcpSocket>
Где это используется?

2023-05-03 22:22 UTC, Ant0nL0rd commented on general_use/include/networkTools.h
> +qint32 getPort(qint32 startRangeSearch = 4000, qint32 stopRangeSearch = 5000, QString ip = "localhost");
Что это за ip-шник такой, почему такое короткое название, почему он не в QHostAddress, зачем такое дефолтное значение и почему оно задано в настолько неочевидном виде?

2023-05-04 12:36 UTC, AlfaIV commented on general_use/sources/networkTools.cpp
> +        assert(port <= 49151);
- [x] Заменил.

2023-05-04 12:37 UTC, AlfaIV commented on general_use/sources/networkTools.cpp
> +        assert(startRangeSearch < stopRangeSearch);
- [x] Заменил

2023-05-04 12:39 UTC, AlfaIV commented on gstreamer_interface/include/SessionManager.h
> +    qint16 getPort();
- [x] Это мусор. Убрал его.

2023-05-04 12:40 UTC, AlfaIV commented on gstreamer_interface/include/SessionManager.h
> +#include <QTcpSocket>
- [x] Тоже мусор. Убрал.

2023-05-04 13:08 UTC, AlfaIV commented on general_use/include/networkTools.h
> +qint32 getPort(qint32 startRangeSearch = 4000, qint32 stopRangeSearch = 5000, QString ip = "localhost");
- [x] Заменил везде на QHostAddress.

2023-05-04 13:20 UTC, AlfaIV commented on application/sources/main.cpp
> +    qDebug() << getPort(4000, 5000);
- [x] Откатил main

2023-05-06 21:12 UTC, Ant0nL0rd approved these changes

2023-05-16 15:25 UTC, merged